version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ristohub-db
    environment:
      POSTGRES_USER: ristohub
      POSTGRES_PASSWORD: ristohub
      POSTGRES_DB: ristohub_db
    ports:
      - "5432:5432"
    volumes:
      - ristohub_pgdata:/var/lib/postgresql/data

  users-service:
    build: ./users-service
    container_name: ristohub-users-service
    environment:
      DATABASE_URL: postgresql://ristohub:ristohub@db:5432/ristohub_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  ristohub_pgdata:
